### ISSUE TITLE
Add storybook

### ISSUE THREAD

**Issue by AbdelrhmanAmin** [MohamedBechirMejri/react-isloading#1]
Hey Mohamed :)

I love your effort, however, I encourage you to add a storybook to allow people to view the loaders.

Best of luck!

**Comment by MohamedBechirMejri** [comment]
hey Abdelrahman, 
    
Thanks for being interested in my work. I'm not familiar with storybook but I will look into it and implement it asap.

Thanks.

**Comment by AbdelrhmanAmin** [comment]
@MohamedBechirMejri Storybook is a tool that allows you to preview and build UI components in separation.
See for example: https://chakra-ui.netlify.app/?path=/story/spinner--default

**Comment by MohamedBechirMejri** [comment]
I added Storybook as a second option to preview the files and will make it the default one after I add customization for the loaders (other than styling).

Thanks Abdelrahman for you contribution. Please share the package with your friends if you like it and don't hesitate to request more features.
